package entity;

import java.util.Date;

public class Ip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip.address
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip.port
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip.speed
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private Integer speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip.response_time
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private Integer responseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip.is_validated
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private Integer isValidated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip.last_validate_time
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private Date lastValidateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip.is_tested
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private Integer isTested;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip.last_test_time
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private Date lastTestTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip.address
     *
     * @return the value of ip.address
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip.address
     *
     * @param address the value for ip.address
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip.port
     *
     * @return the value of ip.port
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip.port
     *
     * @param port the value for ip.port
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip.speed
     *
     * @return the value of ip.speed
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public Integer getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip.speed
     *
     * @param speed the value for ip.speed
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setSpeed(Integer speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip.response_time
     *
     * @return the value of ip.response_time
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public Integer getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip.response_time
     *
     * @param responseTime the value for ip.response_time
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setResponseTime(Integer responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip.is_validated
     *
     * @return the value of ip.is_validated
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public Integer getIsValidated() {
        return isValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip.is_validated
     *
     * @param isValidated the value for ip.is_validated
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setIsValidated(Integer isValidated) {
        this.isValidated = isValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip.last_validate_time
     *
     * @return the value of ip.last_validate_time
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public Date getLastValidateTime() {
        return lastValidateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip.last_validate_time
     *
     * @param lastValidateTime the value for ip.last_validate_time
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setLastValidateTime(Date lastValidateTime) {
        this.lastValidateTime = lastValidateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip.is_tested
     *
     * @return the value of ip.is_tested
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public Integer getIsTested() {
        return isTested;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip.is_tested
     *
     * @param isTested the value for ip.is_tested
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setIsTested(Integer isTested) {
        this.isTested = isTested;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip.last_test_time
     *
     * @return the value of ip.last_test_time
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public Date getLastTestTime() {
        return lastTestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip.last_test_time
     *
     * @param lastTestTime the value for ip.last_test_time
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setLastTestTime(Date lastTestTime) {
        this.lastTestTime = lastTestTime;
    }
}