package entity;

public class UserAgent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agent.id
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agent.string
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private String string;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agent.browser_name
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private String browserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agent.browser_version
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private String browserVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agent.browser_type
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private String browserType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agent.operating_system
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    private String operatingSystem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agent.id
     *
     * @return the value of user_agent.id
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agent.id
     *
     * @param id the value for user_agent.id
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agent.string
     *
     * @return the value of user_agent.string
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public String getString() {
        return string;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agent.string
     *
     * @param string the value for user_agent.string
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setString(String string) {
        this.string = string;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agent.browser_name
     *
     * @return the value of user_agent.browser_name
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public String getBrowserName() {
        return browserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agent.browser_name
     *
     * @param browserName the value for user_agent.browser_name
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setBrowserName(String browserName) {
        this.browserName = browserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agent.browser_version
     *
     * @return the value of user_agent.browser_version
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public String getBrowserVersion() {
        return browserVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agent.browser_version
     *
     * @param browserVersion the value for user_agent.browser_version
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setBrowserVersion(String browserVersion) {
        this.browserVersion = browserVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agent.browser_type
     *
     * @return the value of user_agent.browser_type
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public String getBrowserType() {
        return browserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agent.browser_type
     *
     * @param browserType the value for user_agent.browser_type
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setBrowserType(String browserType) {
        this.browserType = browserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agent.operating_system
     *
     * @return the value of user_agent.operating_system
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public String getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agent.operating_system
     *
     * @param operatingSystem the value for user_agent.operating_system
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }
}