package mapper;

import entity.Ip;
import entity.IpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    long countByExample(IpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    int deleteByExample(IpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    int insert(Ip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    int insertSelective(Ip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    List<Ip> selectByExample(IpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") Ip record, @Param("example") IpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip
     *
     * @mbg.generated Fri Aug 25 22:36:36 CST 2017
     */
    int updateByExample(@Param("record") Ip record, @Param("example") IpExample example);
}